config/routes.rb
Rails.application.routes.draw do
    resources :votes
    resources :communities
    get 'errors/not_found'

    get 'errors/internal_server_error'

    root 'static_pages#home'
    get 'abt'               => 'static_pages#about'
    get 'nr'                => 'static_pages#newsroom'
    get 'h'                 => 'static_pages#help'
    get 'su'                => 'users#new'
    post 'su'               => 'users#create'
    get 'li'                => 'sessions#new'
    post 'li'               => 'sessions#create'
    delete 'lo'             => 'sessions#destroy'
    match '404', :to => 'errors#not_found', :via => :all
    match '500', :to => 'errors#internal_server_error', :via => :all
    get '/u/:username'      => 'users#show'
    get '/u/:username/edit' => 'users#edit'
    patch '/u/:username'    => 'users#update'
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :posts do
        member do
            put 'like'	    => 'posts#like'
        end
    end
    resources :posts, only: [:put, :create, :destroy]
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :relationships,       only: [:create, :destroy]
end

app/models/community.rb
class Community < ApplicationRecord
    has_many :posts, dependent: :destroy # TODO: Determine whether it's a good idea to destroy dependents
    has_many :users
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
      @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
      # Generate list of posts on that community
      @post = current_user.posts.build(community_id: @community.id, user_id: current_user.id)
      @posts = @community.posts.paginate(page: params[:page])
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_for(community) do |f| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Communities</h1>
<div class="grid">
    <% @communities.each do |community| %>
    <div>
        <%# TODO: Use link_to %>
        <a href="<%= community_path(community) %>">
            <div class="community-photo" style="background-image: url(<%= community.photo ? community.photo : 'assets/community.png' %>)"></div>
            <h5><%= community.name %></h5>
        </a>
        <p><%= community.description %></p>
        <p><%= link_to 'Edit', edit_community_path(community) %></p>
        <p><%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
    <% end %>
</div>

<%= link_to 'New Community', new_community_path %>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<% provide(:title, @community.name) %>
<div class="community-info">
    <%= image_tag(@community.photo ? @community.photo : '/assets/community.png', alt: "#{@community.name}'s header photo'") %>
    <h1><%= @community.name %></h1>
    <p><%= @community.description %></p>
    <%# TODO: Only show/allow for privileged users  %>
    <%= link_to 'Edit', edit_community_path(@community) %>
</div>

<%= render 'shared/post_form' %>
<% if @community.posts.any? %>
    <ol class="posts">
        <%= render @posts %>
    </ol>
    <%= will_paginate @posts %>
<% end %>