config/routes.rb
Rails.application.routes.draw do
    resources :votes
    resources :communities
    get 'errors/not_found'

    get 'errors/internal_server_error'

    root 'static_pages#home'
    get 'abt'               => 'static_pages#about'
    get 'nr'                => 'static_pages#newsroom'
    get 'h'                 => 'static_pages#help'
    get 'su'                => 'users#new'
    post 'su'               => 'users#create'
    get 'li'                => 'sessions#new'
    post 'li'               => 'sessions#create'
    delete 'lo'             => 'sessions#destroy'
    match '404', :to => 'errors#not_found', :via => :all
    match '500', :to => 'errors#internal_server_error', :via => :all
    get '/u/:username'      => 'users#show'
    get '/u/:username/edit' => 'users#edit'
    patch '/u/:username'    => 'users#update'
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :posts do
        member do
            put 'like'	    => 'posts#like'
        end
    end
    resources :posts, only: [:put, :create, :destroy]
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
    <p>&copy; <%= Time.now.year %>. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div id="nav-button"><span></span><span></span><span></span></div>
    <nav>
        <ul>
            <% if logged_in? %>
                <li><%= link_to "Feed", root_url %></li>
                <li><%= link_to "Account", '' %>
                    <ul>
                        <li><%= link_to "Profile", user_path(current_user) %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li><%= link_to "Log out", lo_path, method: "delete" %></li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Home", root_url %></li>
                <li><%= link_to "Sign Up", su_path %></li>
                <li><%= link_to "Log in", li_path %></li>
            <% end %>
            <li><%= link_to "About", abt_path %></li>
            <li><%= link_to "Contact", h_path %></li>
        </ul>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
</head>

<body class="<%= yield(:pagetype) + ' ' + yield(:colorscheme) %>" style="<% if yield(:backgroundimage).length > 0 %>background-image: url(<%= asset_path "assets/bg/#{yield(:backgroundimage)}.jpg" %>);<% end %>">
    <%= render 'layouts/header' %>
    <article>
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
    </article>
    <%= render 'layouts/footer' %>
</body>

</html>